- name: nginx install and run
  hosts: web
  become: yes
  tasks:
  - name: install nginx
    ansible.builtin.package: #heterogenous modeuls that can work for all distributions
      name: nginx
      state: absent