- name: variables from prompt
  hosts: web
  vars: 
    COURSE: "Devops with AWS from PLAY level"
    DURATION: "120Hrs"
  #vars_files:
  #- vars.yaml
  vars_prompt:
  - name: COURSE
    prompt: Please enter the course name
    private: false
  - name: DURATION
    prompt: Please enter the duration
    private: false
  tasks:
  - name: print the course information
    vars: 
      #COURSE: "Devops with AWS from TASK level"
      #DURATION: "120Hrs"
    ansible.builtin.debug:
      msg: "Hi, I am learning {{COURSE}} for about {{DURATION}}"

#args
#task level
#files

