- name: create user
  hosts: web
  become: yes
  tasks:
  - name: check user exists or not
    ansible.builtin.command: id expense
    register: USER # USER is the variable that gets output from the above command

  - name: print the user information
    ansible.builtin.debug:
      msg: "user info: {{ USER }}"