- name: filters/functions
  hosts: local
  connection: local
  tasks:
  - name: print teh defaault variable
    ansible.builtin.debug:
      msg: "{{ course | default('Ansible') }}"
  
  - name: convert to uppercase
    vars: 
      greeting: "Hello Ramesh"
    ansible.builtin.debug:
      msg: "{{ greeting | upper }}"

  - name: convert to lowercase
    vars: 
      greeting: "Hello Ramesh"
    ansible.builtin.debug:
      msg: "{{ greeting | lower }}"

  - name: get the unique values
    vars:
      numbers: [1,2,3,4,5,6,4,3,2]
    ansible.builtin.debug:
      msg:  "{{ numbers | unique }}"

  - name: get the min and max
    vars:
      numbers: [1,2,3,4,5,6,4,3,2]
    ansible.builtin.debug:
      msg:  "Min: {{ numbers | min }}, Max: {{ numbers | max }}"

  - name: convert map to list
    vars:
      course:
        name: "Devops with AWS"
        duration: 120
        trainer: "praveena"
    tasks:
      ansible.buitin.debug:
        msg: "{{ course | dict2items }}"